version: '3.3'
services:

  first_fork:
    container_name: first_fork
    image: oraichain/foundation-gravity-fork:0.0.1
    working_dir: /workspace
    restart: on-failure
    ports:
      - 8545:8545
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./:/workspace
      - ./hardhat-first-fork.config.ts:/workspace/hardhat.config.ts
    command: yarn hardhat node

  second_fork:
    container_name: second_fork
    image: oraichain/foundation-gravity-fork:0.0.1
    working_dir: /workspace
    restart: on-failure
    ports:
      - 7545:8545
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./:/workspace
      - ./hardhat-second-fork.config.ts:/workspace/hardhat.config.ts
    command: yarn hardhat node
