version: '3.3'
services:
  oraibridge:
    container_name: oraibridge
    image: orai/gravity-base-prod:0.2
    command: tail -f /dev/null
    environment:
      - VALIDATOR=validator1
      - CHAIN_ID=oraibridge-test
      - GRAVITY_HOME=/workspace/data
      - ADDRESS_PREFIX=oraib
    working_dir: /workspace
    volumes:
      - ./:/workspace
      # map first node data to .workspace folder
    ports:
      - 26657:26657
      - 9090:9090
    tty: true
