[package]
name = "proto_build"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"


[dependencies]
prost-build = "0.11"
walkdir = "2"
tonic-build = "0.8"
regex = "1.5"
