[package]
name = "proto_build"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"


[dependencies]
prost = "0.11.5"
tonic = "0.8.3"
prost-build = "0.11.5"
walkdir = "2"
tonic-build = "0.8.3"
regex = "1.5"
