name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: module/go.sum
          go-version-file: module/go.mod
      - name: Build
        run: cd module && make

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: module/go.sum
          go-version-file: module/go.mod
      - name: Install golang-lint 
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Build
        run: cd module && golangci-lint run -c .golangci.yml --disable-all --timeout=30m && go mod verify

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache-dependency-path: module/go.sum
          go-version-file: module/go.mod
      - name: Test
        run: cd module && go test ./... -mod=readonly -timeout 30m -coverprofile=profile.out -covermode=atomic -race
