name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: cd module && make

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install golang-lint 
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Build
        run: cd module && golangci-lint run -c .golangci.yml --disable-all --timeout=3m && go mod verify

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - uses: actions/checkout@v2
      - name: Test
        run: cd module && go test ./... -mod=readonly -timeout 30m -coverprofile=profile.out -covermode=atomic -race
