name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a .proto file has been changed
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@master
      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            **/**.proto
      - name: lint
        run: cd module && make proto-lint
        if: env.GIT_DIFF
